# Etapa 1: Build da aplicação
FROM node:lts-alpine AS builder

WORKDIR /app
COPY . .
RUN npm ci
RUN npm run build

# Etapa 2: Imagem final apenas com arquivos estáticos
FROM nginx:alpine

# Remove a configuração default do nginx
RUN rm -rf /usr/share/nginx/html/*

# Copia os arquivos estáticos gerados pelo Vite
COPY --from=builder /app/dist /usr/share/nginx/html

# Exponha a porta padrão do nginx
EXPOSE 80

# Comando para iniciar o nginx
CMD ["nginx", "-g", "daemon off;"]