# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - produtos

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      #- name: npm install, build, and test
      #  run: |
      #    cd backend/ # <--- ADICIONADO: Entra na pasta backend
      #    npm install
      #    npm run build --if-present
      #    npm run test --if-present
      #  # working-directory: './backend' # <--- REMOVIDO: Não é mais necessário aqui, pois usamos 'cd'

      - name: Zip artifact for deployment
        run: |
          cd backend/ # <--- ADICIONADO: Entra na pasta backend
          mkdir ./dist
          cp ./index.js ./dist
          cp ./package*.json ./dist
          
          zip release.zip ./dist/* -r
        # working-directory: './backend' # <--- REMOVIDO: Não é mais necessário aqui, pois usamos 'cd'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: './backend/release.zip' # <--- CAMINHO CORRIGIDO AQUI!

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      #- name: Login to Azure
      #  uses: azure/login@v2
      #  with:
      #    client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0A0AE0F96F1E44F58B5E26378F2375ED }}
      #    tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EA0F9EEE8BBA4183BAA5F090AB71904D }}
      #    subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A5EACE59A9D64E85B6DD4252FFB65959 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'produto'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          slot-name: 'Production'
          package: .




